name: myphoneconnection
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  photo_gallery: '^2.2.1'
  flutter_background_service: ^5.0.9
  flutter_secure_storage: ^9.2.2
  network_info_plus: ^6.0.1
  device_info_plus: ^10.1.0
  pointycastle: ^3.9.1
  web_socket_channel: ^3.0.0
  flutter_image_compress: ^2.3.0
  archive: ^3.6.1
  http: ^1.2.2
  path_provider: ^2.1.4
  device_apps: ^2.2.0
  super_clipboard: ^0.8.19
  notification_listener_service: ^0.3.3
  audio_service: ^0.18.15
  awesome_notifications: ^0.9.3+1
  phone_state: ^1.0.4
  contacts_service: ^0.6.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.3.0

flutter:
  uses-material-design: true
